### ISSUE TITLE
Enable the use of the "send" method on the configuration object

### ISSUE THREAD

**Issue by fusillicode** [beatrichartz/configurations#10]
While trying to set up a bunch of options identified by variables name I got stuck with the inability to use the method "send".

Here's the problematic snippet of code:
```
MyGem.configure do |c|
    # 'configs' and 'cli_options' are just two hashes. I've left out their construction to focus on the key point of the issue
    configs.deep_merge(cli_options).map do |key, value|
      c.send "#{key}=", value
    end
  end
end
```
If I've left out some important information or if the issue isn't appropriate for some reasons please forgive me.

Cheers.

**Comment by beatrichartz** [comment]
Hi there!

You can use [`from_h`](http://www.rubydoc.info/gems/configurations/Configurations/Configuration#from_h-instance_method) to achieve what you want to do:

```ruby
MyGem.configure do |c|
  c.from_h(configs.deep_merge(cli_options))
end
```
If your configuration is using strict mode (defined attributes), you can use a shorthand:

```ruby
MyGem.configuration.from_h(configs.deep_merge(cli_options))
```

If you still want to use send, use [`__send__`](http://ruby-doc.org/core-2.2.2/Object.html#method-i-send)

Cheers

**Comment by fusillicode** [comment]
Ty a lot for the quick reply!

I think I'm missing something here. I've already tried with `from_h` but it doesn't works. 

If I try to access a configuration value I get `nil` in response :(

**Comment by fusillicode** [comment]
Ok, got it!

The problem are the hash keys. They're strings, not symbols. 

Now I've only a "design" question. Personally I think it would be great if `configurations` would handle transparently strings as well as symbols. From the other side I also think that the user should worry to supply the correct input to the gem.

What do you think? Would you accept a pull request to add this "sugar" to the gem?

P.S: forgive again for the bother and ty again for your helpfulness.

**Comment by beatrichartz** [comment]
Cool. I'll put some thought into handling strings in `from_h` - the fact it does not handle strings is more incidental atm.

**Comment by fusillicode** [comment]
Roger that.

Anyway, jftr, a quick fix could be to explicitly transform the `property` passed to the `__assign!` method in the `Configuration` class (line 153) to a symbol.

If there is something I can do let me know, I'll stick around ;)

Ty again.

**Comment by beatrichartz** [comment]
Released configuration with hashes with string keys in `2.1.0`.
