### ISSUE TITLE
Configuration is reset and unavailable in railtie

### ISSUE THREAD

**Issue by artgo** [beatrichartz/configurations#12]
If you have your gem as plugin as railtie and install the gem, after initializer configuration is run (and I can print out values there) if I attempt to access the values again in controller added by the gem - the values are not available and are reset to initial values.

**Comment by beatrichartz** [comment]
Could you provide code or more context on what you are trying to achieve?

Provided the configuration code is run on initialization and the modules are not reloaded, the configurations should not be reset.

**Comment by artgo** [comment]
Repro steps are: 
1. Generate a new rails gem based on rails engine as describe here: http://guides.rubyonrails.org/engines.html

2. Create a new controller /app/controllers/mygem/mycontroller.rb

3. add the controller into routes
```
Rails.application.routes.draw do
  match '/my/api/call' => 'mygem/mycontroller#call', via: [:get]
end
```

4. In controller method call:
```
def call
  puts Mygem.configuration.mystring
end
```

5. In gem's main class
lib/mygem.rb follow your instructions:
```
require 'configuration'
module Mygem
   include Configuration

  configurable String, :mystring
  configurable String, :anotherstring

  configuration_defaults do |c|
    c.anotherstring = 'some'
  end

  not_configured :mystring do |prop| # omit the arguments to get a catch-all not_configured
    raise ArgumentError, "Please configure #{prop}"
  end
end
```

6. Create rails 4.1 app and include the newly create gem into Gemfile

7. create initializer config/initializers/mygem.rb
```
Mygem.configure do |c|
  c.mystring = 'mystr'
end

puts Mygem.configuration.mystring
```

8. Setup newly created rails app to use puma

9. Run the rails app and try to access /my/api/call

You'll see that the variable IS configured (from output in initializer) but attempt to access it in controller returns uninitialized version.

**Comment by beatrichartz** [comment]
Sharing nothing between threads does not play well with puma / webrick - I changed the implementation to be synchronized which should be more in line with ruby standards.

Could you retry with release `2.2.0` and let me know if any issues persist? I tried your example with webrick, thin, puma and unicorn and it works for me.

**Comment by artgo** [comment]
yeah, your fix worked :)
