### ISSUE TITLE
Deadlock issue!

### ISSUE THREAD

**Issue by Exelord** [beatrichartz/configurations#14]
Hi,
I found an issue with deadlock.

If I want to use sth like:

`app/models/mygem/project.rb`
``` ruby
class Mygem::Project < ActiveRecord::Base
  has_many :users, class_name: "::#{Mygem.configuration.user_class}"
end
```

I get `'synchronize': deadlock; recursive locking (ThreadError)`

Can you check it out? Thanks a lot! 
Its currently blocking my work on that epic gem - [Monarchy](https://github.com/Exelord/Monarchy)

**Comment by beatrichartz** [comment]
Hi, I'm currently away without access to a desktop - will check this out in about 2 weeks.

From a distance, it seems like ActiveRecord maybe puts a lock on class definitions(?), you could try invoking the getter on the configuration outside ActiveRecord and then assign the variable inside.

**Comment by beatrichartz** [comment]
Like so:

```
user_class = Mygem.configuration.user_class
class Mygem::Project < ActiveRecord::Base
  has_many :users, class_name: "::#{user_class}"
end
```

**Comment by Exelord** [comment]
I try that solution but it does not help :/
I'm getting the error.

The problem is still the same. I can not access `Mygem.configuration`.
I can not also use some classes in the config - whats wired sometimes some of them were not already initialized.

For further debugging you can look to my code. Specyfic branch:
https://github.com/Exelord/Monarchy/tree/feature-dynamic-classes
or to compared changes: 
https://github.com/Exelord/Monarchy/pull/38

**Comment by beatrichartz** [comment]
My best guess is that these classes are  autoloaded via active support as soon as you call configuration - does the same occur with POROs? If not an explicit require might help.

**Comment by beatrichartz** [comment]
Looking at this a bit more closely I'm not sure whether setting the member or user class in the configuration is the way you want this to work.

When you do it this way, the classes will depend on configuration happening *before* the classes get loaded, however in a Rails ecosystem that is not a given, so your gem could end up misconfigured.

I think the more idiomatic way to provide these load time dependencies would be via the class method of the mixin, like so:

```
acts_as_hierarchy member_class: 'Member'
```

**Comment by Exelord** [comment]
Hey! 
Thanks for pointing me the right direction. I had an issue with passing config vars as Classes. They are inherited from classes which needed config options.

Anyway... a ⭐  for you! Great!

**Comment by beatrichartz** [comment]
Glad I could help :)
