### ISSUE TITLE
Intermittently fails

### ISSUE THREAD

**Issue by dnajd** [beatrichartz/configurations#16]
I have this gem mixed into a class 

```
module MyMod
  extend ActiveSupport::Concern

  # configuration
  include Configurations
  configurable :url
  configuration_defaults do |c|
    c.url = 'https://default.com'
  end
end
```

and I have a unit test that checks the configuration values

```
 # configure
MyMod.configure do |c|
  c.url = 'http://test.com'
end

# has settings?
assert_equal 'http://test.com', MyMod.configuration.url
```

This test intermittently fails with

```
1) Failure:
MyModTest#test_default_configuration
--- expected
+++ actual
@@ -1,2 +1,2 @@
 # encoding: US-ASCII
-"https://default.com"
+"http://test.com"
```

It passes more than half the time, but if I run it enough times it fails.  Any idea why?

**Comment by beatrichartz** [comment]
I tried to reproduce this failure using the following script:

```ruby
require 'configurations'
require 'active_support'

module MyMod
  extend ActiveSupport::Concern
  include Configurations

  configurable :url

  configuration_defaults do |c|
    c.url = 'https://default.com'
  end
end

MyMod.configure do |c|
  c.url = 'http://test.com'
end

if MyMod.configuration.url != 'http://test.com'
  puts "Uh-oh! MyMod.configuration.url is #{MyMod.configuration.url} !"
else
  print "."
end
```

I've been using
- configurations `2.2.1`
- activesupport `5.0.0.1`

And executing the script on the latest MRI, jRuby and Rubinius platforms using:

```bash
for i in {1..1000}; do ruby test.rb; done
```

Without getting any errors. Can you specify what setup you are running (Version of configurations & activesupport, ruby platform & version)?

**Comment by beatrichartz** [comment]
Closing this - feel free to reopen if we're able to reproduce.
